/*
 * Copyright (C) 2015 Emanuel Martinez Pinzon
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ufps.is.poo.presentacion;

import ufps.is.poo.negocio.Competencia;
import ufps.is.poo.util.Notificacion;

/**
 * Este es el panel para eliminar propietarios de la interfaz grafica de la aplicacion.
 * @author Emanuel Martinez Pinzon
 */
public final class eliminarPropietarioPanel extends javax.swing.JPanel {

    private Competencia competencia;
    
   public eliminarPropietarioPanel(Competencia competencia) {
        this.competencia = competencia;
        initComponents();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbPlacaEliminarPropietario = new javax.swing.JComboBox();
        cmbAñoEliminarPropietario = new javax.swing.JComboBox();
        cmbPropietarioEliminarPropietario = new javax.swing.JComboBox();
        cmdEliminarPropietario = new javax.swing.JButton();
        cmdEliminarTodosPropietarios = new javax.swing.JButton();
        cmdEliminarTodosPropietarioAño = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eliminar propietario");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Elimina un propietario del sistema");

        jLabel3.setText("Placa: ");

        jLabel4.setText("Propietario: ");

        jLabel5.setText("Año: ");

        cmbPlacaEliminarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlacaEliminarPropietarioActionPerformed(evt);
            }
        });

        cmbAñoEliminarPropietario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));

        cmdEliminarPropietario.setText("Eliminar");
        cmdEliminarPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarPropietarioActionPerformed(evt);
            }
        });

        cmdEliminarTodosPropietarios.setText("Todos");
        cmdEliminarTodosPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarTodosPropietariosActionPerformed(evt);
            }
        });

        cmdEliminarTodosPropietarioAño.setText("Año");
        cmdEliminarTodosPropietarioAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarTodosPropietarioAñoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPlacaEliminarPropietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPropietarioEliminarPropietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAñoEliminarPropietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdEliminarTodosPropietarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEliminarTodosPropietarioAño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdEliminarPropietario)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPlacaEliminarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbAñoEliminarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbPropietarioEliminarPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdEliminarPropietario)
                    .addComponent(cmdEliminarTodosPropietarios)
                    .addComponent(cmdEliminarTodosPropietarioAño))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEliminarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarPropietarioActionPerformed
        String placa = cmbPlacaEliminarPropietario.getSelectedItem().toString();
        String anio = cmbAñoEliminarPropietario.getSelectedItem().toString();
        String propietario = cmbPropietarioEliminarPropietario.getSelectedItem().toString();

        if(competencia.borrarPropietario(placa, Integer.parseInt(anio), propietario))
            Notificacion.alertaInformativo("Sistema", "Propietario eliminado con exito.");
        else
            Notificacion.alertaAtencion("Sistema", "Algo no se ha hecho bien y no se han efectuado cambios");
    }//GEN-LAST:event_cmdEliminarPropietarioActionPerformed

    private void cmdEliminarTodosPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarTodosPropietariosActionPerformed
        String placa = cmbPlacaEliminarPropietario.getSelectedItem().toString();
        
        if(competencia.borrarTodosPropietario(placa))
            Notificacion.alertaInformativo("Sistema", "Todos los propietarios eliminados");
        else
            Notificacion.alertaAtencion("Sistema", "Algo no se ha hecho bien y no se han efectuado cambios");
    }//GEN-LAST:event_cmdEliminarTodosPropietariosActionPerformed

    private void cmdEliminarTodosPropietarioAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarTodosPropietarioAñoActionPerformed
        String placa = cmbPlacaEliminarPropietario.getSelectedItem().toString();
        String anio = cmbAñoEliminarPropietario.getSelectedItem().toString();

        if(competencia.borrarTodosPropietario(placa, Integer.parseInt(anio)))
            Notificacion.alertaInformativo("Sistema", "Todos los propietarios del año "+anio+" eliminados");
        else
            Notificacion.alertaAtencion("Sistema", "Algo no se ha hecho bien y no se han efectuado cambios");
    }//GEN-LAST:event_cmdEliminarTodosPropietarioAñoActionPerformed

    private void cmbPlacaEliminarPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlacaEliminarPropietarioActionPerformed
        String placa = cmbPlacaEliminarPropietario.getSelectedItem().toString();
        String anio = cmbAñoEliminarPropietario.getSelectedItem().toString();
        String []propietario = competencia.concatenarPropietarios(placa, Integer.parseInt(anio)).split("~");
        cmbPropietarioEliminarPropietario.removeAllItems();
        for(String x: propietario)
            cmbPropietarioEliminarPropietario.addItem(x);
    }//GEN-LAST:event_cmbPlacaEliminarPropietarioActionPerformed

    public void llenarCombo(){
        String []nombres = competencia.concatenarplacas().split("~");
        cmbPlacaEliminarPropietario.removeAllItems();
        for(String x: nombres)
            cmbPlacaEliminarPropietario.addItem(x);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbAñoEliminarPropietario;
    private javax.swing.JComboBox cmbPlacaEliminarPropietario;
    private javax.swing.JComboBox cmbPropietarioEliminarPropietario;
    private javax.swing.JButton cmdEliminarPropietario;
    private javax.swing.JButton cmdEliminarTodosPropietarioAño;
    private javax.swing.JButton cmdEliminarTodosPropietarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
